### ISSUE TITLE
Cambiar condición para diferencia de decimales

### ISSUE THREAD

**Issue by erickfmm** [blackopa/Practica_II#15]
https://github.com/blackopa/Practica_II/blob/53568291b056067486aa5960361ec1675ca3272e/mainapp/validations/Funciones_datos.py#L58

Cambiar de
metros != round(float(metros_tabla_resumen.replace(',','.')),1))

A:
abs(metros - round(float(metros_tabla_resumen.replace(',','.')),1)) ) < 0.01

También en todas las otras comparaciones

**Comment by blackopa** [comment]
Agregada la condición en la comparación de los metros.
