### ISSUE TITLE
Cambiar la variable "i" por otro nombre

### ISSUE THREAD

**Issue by erickfmm** [blackopa/Practica_II#6]
En: https://github.com/blackopa/Practica_II/blob/bef51c849f42dec43018b662c782830e030a51b9/mainapp/validations/Informe_datos.py#L36

Se está usando una variable de nombre "i" dentro de un for que ya tiene como variable el nombre "i", por lo que se sobreescribe, que si bien en este caso particular funciona, no es una buena práctica (funciona ya que i toma los valores de un arreglo y no es una variable que se auto modifique, además que bajo el segundo for no hay código que pertenezca al for externo)
Sugiero cambiar el nombre de la variable a algo más descriptivo como "i_linea" y el i de arriba a "i_pagina" o nombres similares, para así evitar confusiones y posibles errores a futuro

**Comment by blackopa** [comment]
Revisado y cambiado en el código
